# codegen/x86_generator.py
"""
Генератор x86-64 ассемблерного кода из IR представления.
Следует соглашениям System V AMD64 ABI.
Поддерживает int и float операции.
"""

import sys
import struct
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from ir.ir_instructions import IROpcode, IROperandType
from .stack_frame import StackFrame


class X86Generator:
    def __init__(self, ir_program):
        self.ir_program = ir_program
        self.output = []
        self.current_stack_frame = None
        self.current_function_name = None
        self.string_literals = []
        self.float_literals = []
        self.emitted_labels = set()
        self.param_to_temp = {}
        self.pending_params = []

    def generate(self) -> str:
        self.output = []
        self.float_literals = []

        self.output.append("; Generated by MiniCompiler")
        self.output.append("; Target: x86-64 Linux, System V AMD64 ABI")
        self.output.append("")

        self._generate_data_section()

        self.output.append("section .text")
        self.output.append("extern print_int, print_string, read_int, exit")
        self.output.append("")

        for func in self.ir_program.functions:
            self._generate_function(func)

        if self.float_literals:
            self.output.append("")
            self.output.append("section .rodata")
            for label, val in self.float_literals:
                # float как 32-bit single precision
                bits = struct.unpack('>I', struct.pack('>f', val))[0]
                self.output.append(f"{label}: dd {bits}  ; float {val}")

        return "\n".join(self.output)

    def _generate_data_section(self):
        bss_lines = []
        data_lines = []

        for name, var in self.ir_program.global_vars.items():
            if hasattr(var, 'ir_type') and var.ir_type:
                type_name = var.ir_type.name if hasattr(var.ir_type, 'name') else 'int'
                if type_name == 'int':
                    bss_lines.append(f"    {name}: resd 1")
                elif type_name == 'float':
                    data_lines.append(f"    {name}: dd 0.0")
                elif type_name == 'bool':
                    bss_lines.append(f"    {name}: resb 1")
                else:
                    bss_lines.append(f"    {name}: resq 1")
            else:
                bss_lines.append(f"    {name}: resq 1")

        if bss_lines:
            self.output.append("section .bss")
            for line in bss_lines:
                self.output.append(line)
            self.output.append("")

        if data_lines:
            self.output.append("section .data")
            for line in data_lines:
                self.output.append(line)
            self.output.append("")

    def _is_float_type(self, operand) -> bool:
        """Проверяет, является ли операнд float по его IR типу."""
        if hasattr(operand, 'ir_type') and operand.ir_type:
            type_name = operand.ir_type.name if hasattr(operand.ir_type, 'name') else ''
            return type_name == 'float'
        return False

    def _is_float_op_str(self, op_str: str) -> bool:
        """Проверяет, является ли строка операнда float литералом."""
        return 'LC' in op_str

    def _make_label(self, label: str) -> str:
        if label.startswith('.'):
            return label
        return f"{self.current_function_name}.{label}"

    def _generate_function(self, func):
        self.current_function_name = func.name
        self.current_stack_frame = StackFrame()
        self.emitted_labels = set()
        self.param_to_temp = {}
        self.pending_params = []

        # Маппинг параметров
        for block in func.blocks:
            for instr in block.instructions:
                if instr.opcode == IROpcode.MOVE:
                    dest = instr.operands[0]
                    src = instr.operands[1]
                    if src.operand_type == IROperandType.VARIABLE:
                        for param in func.parameters:
                            if param.value == src.value:
                                self.param_to_temp[param.value] = dest.value
                                break

        # Собираем временные переменные и их типы
        temps_in_func = {}
        for block in func.blocks:
            for instr in block.instructions:
                for op in instr.operands:
                    if op.operand_type == IROperandType.TEMPORARY:
                        size = 4  # default int
                        if self._is_float_type(op):
                            size = 4  # float = 4 байта (single precision)
                        temps_in_func[op.value] = max(temps_in_func.get(op.value, 4), size)

        for temp_name, size in temps_in_func.items():
            self.current_stack_frame.allocate(temp_name, size)

        # Локальные переменные
        for name, var_type in func.local_vars.items():
            size = 4
            if hasattr(var_type, 'size_bytes'):
                size = var_type.size_bytes
            elif hasattr(var_type, 'name'):
                type_sizes = {'int': 4, 'float': 4, 'bool': 1}
                size = type_sizes.get(var_type.name, 8)
            self.current_stack_frame.allocate(name, size)

        # Параметры
        for param in func.parameters:
            param_name = param.value if hasattr(param, 'value') else str(param)
            param_size = 4  # int и float по 4 байта в 32-bit режиме
            if hasattr(param, 'ir_type') and param.ir_type:
                type_name = param.ir_type.name if hasattr(param.ir_type, 'name') else 'int'
                if type_name == 'float':
                    param_size = 4

            if param_name in self.param_to_temp:
                temp_name = self.param_to_temp[param_name]
                temp_offset = self.current_stack_frame.get_offset(temp_name)
                if temp_offset is not None:
                    self.current_stack_frame.variables[param_name] = (temp_offset, param_size)
            elif param_name not in self.current_stack_frame.variables:
                self.current_stack_frame.allocate(param_name, param_size)

        # Пролог
        self.output.append(f"global {func.name}")
        self.output.append(f"{func.name}:")
        self._emit("push rbp")
        self._emit("mov rbp, rsp")

        total_size = self.current_stack_frame.get_total_size()
        if total_size > 0:
            self._emit(f"sub rsp, {total_size}")

        self._save_parameters(func)

        # Тело функции
        for block in func.blocks:
            unique_label = self._make_label(block.label)
            if unique_label not in self.emitted_labels:
                self.emitted_labels.add(unique_label)
                self.output.append(f"{unique_label}:")

            for instr in block.instructions:
                if instr.opcode == IROpcode.ALLOCA:
                    continue

                if instr.opcode == IROpcode.MOVE:
                    src = instr.operands[1]
                    if src.operand_type == IROperandType.VARIABLE:
                        is_param = any(p.value == src.value for p in func.parameters)
                        if is_param:
                            continue

                if instr.opcode == IROpcode.PARAM:
                    self.pending_params.append(instr)
                    continue

                if instr.opcode == IROpcode.CALL:
                    for param_instr in self.pending_params:
                        asm = self._translate_instruction(param_instr, func)
                        if asm:
                            for line in asm.split('\n'):
                                line = line.strip()
                                if line:
                                    self._emit(line)
                    self.pending_params = []

                    asm = self._translate_instruction(instr, func)
                    if asm:
                        for line in asm.split('\n'):
                            line = line.strip()
                            if line:
                                self._emit(line)

                    dest = instr.operands[0]
                    if dest.operand_type == IROperandType.TEMPORARY:
                        dest_str = self._op(dest)
                        is_float = self._is_float_type(dest)
                        if is_float:
                            self._emit(f"movss {dest_str}, xmm0")
                        else:
                            self._emit(f"mov {dest_str}, eax")
                    continue

                asm = self._translate_instruction(instr, func)
                if asm:
                    for line in asm.split('\n'):
                        line = line.strip()
                        if line:
                            self._emit(line)

        # Эпилог
        return_label = self._make_label(f"{func.name}_return")
        if return_label not in self.emitted_labels:
            self.emitted_labels.add(return_label)
            self.output.append(f"{return_label}:")
        self._emit("mov rsp, rbp")
        self._emit("pop rbp")
        self._emit("ret")
        self.output.append("")

    def _save_parameters(self, func):
        """Сохраняет параметры функции из регистров в стек."""
        int_regs = ['edi', 'esi', 'edx', 'ecx', 'r8d', 'r9d']
        float_regs = ['xmm0', 'xmm1', 'xmm2', 'xmm3', 'xmm4', 'xmm5', 'xmm6', 'xmm7']
        int_idx = 0
        float_idx = 0

        for param in func.parameters:
            param_name = param.value if hasattr(param, 'value') else str(param)
            offset = self.current_stack_frame.get_offset(param_name)
            if offset is None:
                continue

            is_float = self._is_float_type(param)

            if is_float and float_idx < len(float_regs):
                self._emit(f"movss dword [rbp{offset}], {float_regs[float_idx]}")
                float_idx += 1
            elif not is_float and int_idx < len(int_regs):
                self._emit(f"mov dword [rbp{offset}], {int_regs[int_idx]}")
                int_idx += 1

    def _translate_instruction(self, instr, func):
        opcode = instr.opcode
        ops = instr.operands

        is_float = self._is_float_type(ops[0]) if ops else False

        if opcode == IROpcode.MOVE:
            dest = self._op(ops[0])
            src = self._op(ops[1])
            if dest == src:
                return None

            is_float_move = self._is_float_type(ops[0]) or self._is_float_type(ops[1]) or self._is_float_op_str(src)
            if is_float_move:
                return f"movss xmm0, {src}\n    movss {dest}, xmm0"
            else:
                return f"mov eax, {src}\n    mov {dest}, eax"

        elif opcode == IROpcode.RETURN:
            if ops:
                ret_val = self._op(ops[0])
                ret_label = self._make_label(f"{func.name}_return")
                if self._is_float_type(ops[0]):
                    return f"movss xmm0, {ret_val}\n    jmp {ret_label}"
                return f"mov eax, {ret_val}\n    jmp {ret_label}"
            else:
                ret_label = self._make_label(f"{func.name}_return")
                return f"xor eax, eax\n    jmp {ret_label}"

        elif opcode == IROpcode.CALL:
            return f"call {ops[1].value}"

        elif opcode == IROpcode.PARAM:
            idx = ops[0].value
            if isinstance(idx, int):
                val = self._op(ops[1])
                is_float_param = self._is_float_type(ops[1]) or self._is_float_op_str(val)
                if is_float_param:
                    float_regs = ['xmm0', 'xmm1', 'xmm2', 'xmm3', 'xmm4', 'xmm5', 'xmm6', 'xmm7']
                    if idx < len(float_regs):
                        return f"movss {float_regs[idx]}, {val}"
                else:
                    int_regs = ['edi', 'esi', 'edx', 'ecx', 'r8d', 'r9d']
                    if idx < len(int_regs):
                        return f"mov {int_regs[idx]}, {val}"
            return None

        elif opcode == IROpcode.JUMP:
            target = self._make_label(ops[0].value)
            return f"jmp {target}"

        elif opcode == IROpcode.JUMP_IF:
            cond = self._op(ops[0])
            target = self._make_label(ops[1].value)
            return f"cmp {cond}, 0\n    jne {target}"

        elif opcode == IROpcode.JUMP_IF_NOT:
            cond = self._op(ops[0])
            target = self._make_label(ops[1].value)
            return f"cmp {cond}, 0\n    je {target}"

        elif opcode == IROpcode.ADD:
            dest = self._op(ops[0])
            src1 = self._op(ops[1])
            src2 = self._op(ops[2])
            if is_float:
                if dest == src1:
                    return f"addss {dest}, {src2}"
                return f"movss xmm0, {src1}\n    addss xmm0, {src2}\n    movss {dest}, xmm0"
            else:
                if dest == src1:
                    return f"add {dest}, {src2}"
                return f"mov eax, {src1}\n    add eax, {src2}\n    mov {dest}, eax"

        elif opcode == IROpcode.SUB:
            dest = self._op(ops[0])
            src1 = self._op(ops[1])
            src2 = self._op(ops[2])
            if is_float:
                if dest == src1:
                    return f"subss {dest}, {src2}"
                return f"movss xmm0, {src1}\n    subss xmm0, {src2}\n    movss {dest}, xmm0"
            else:
                if dest == src1:
                    return f"sub {dest}, {src2}"
                return f"mov eax, {src1}\n    sub eax, {src2}\n    mov {dest}, eax"

        elif opcode == IROpcode.MUL:
            dest = self._op(ops[0])
            src1 = self._op(ops[1])
            src2 = self._op(ops[2])
            if is_float or self._is_float_op_str(src1) or self._is_float_op_str(src2):
                if dest == src1:
                    return f"mulss {dest}, {src2}"
                return f"movss xmm0, {src1}\n    mulss xmm0, {src2}\n    movss {dest}, xmm0"
            else:
                if dest == src1:
                    return f"imul {dest}, {src2}"
                return f"mov eax, {src1}\n    imul eax, {src2}\n    mov {dest}, eax"

        elif opcode == IROpcode.DIV:
            dest = self._op(ops[0])
            left = self._op(ops[1])
            right = self._op(ops[2])
            if is_float:
                if dest == left:
                    return f"divss {dest}, {right}"
                return f"movss xmm0, {left}\n    divss xmm0, {right}\n    movss {dest}, xmm0"
            else:
                if not any(c in right for c in ['[', 'dword', 'qword']):
                    return f"mov ecx, {right}\n    mov eax, {left}\n    cqo\n    idiv ecx\n    mov {dest}, eax"
                return f"mov eax, {left}\n    cqo\n    idiv {right}\n    mov {dest}, eax"

        elif opcode == IROpcode.MOD:
            dest = self._op(ops[0])
            left = self._op(ops[1])
            right = self._op(ops[2])
            if not any(c in right for c in ['[', 'dword', 'qword']):
                return f"mov ecx, {right}\n    mov eax, {left}\n    cqo\n    idiv ecx\n    mov {dest}, edx"
            return f"mov eax, {left}\n    cqo\n    idiv {right}\n    mov {dest}, edx"

        elif opcode == IROpcode.NEG:
            dest = self._op(ops[0])
            src = self._op(ops[1])
            if is_float:
                return f"movss xmm0, {src}\n    xorps xmm0, xmm0\n    subss xmm0, {src}\n    movss {dest}, xmm0"
            if dest == src:
                return f"neg {dest}"
            return f"mov eax, {src}\n    neg eax\n    mov {dest}, eax"

        elif opcode == IROpcode.NOT:
            dest = self._op(ops[0])
            src = self._op(ops[1])
            if dest == src:
                return f"not {dest}"
            return f"mov eax, {src}\n    not eax\n    mov {dest}, eax"

        elif opcode in [IROpcode.CMP_EQ, IROpcode.CMP_NE, IROpcode.CMP_LT,
                        IROpcode.CMP_LE, IROpcode.CMP_GT, IROpcode.CMP_GE]:
            dest = self._op(ops[0])
            left = self._op(ops[1])
            right = self._op(ops[2])
            setcc_map = {
                IROpcode.CMP_EQ: "sete", IROpcode.CMP_NE: "setne",
                IROpcode.CMP_LT: "setl", IROpcode.CMP_LE: "setle",
                IROpcode.CMP_GT: "setg", IROpcode.CMP_GE: "setge"
            }
            return f"mov eax, {left}\n    cmp eax, {right}\n    {setcc_map[opcode]} al\n    movzx eax, al\n    mov {dest}, eax"

        elif opcode == IROpcode.AND:
            dest = self._op(ops[0])
            src1 = self._op(ops[1])
            src2 = self._op(ops[2])
            if dest == src1:
                return f"and {dest}, {src2}"
            return f"mov eax, {src1}\n    and eax, {src2}\n    mov {dest}, eax"

        elif opcode == IROpcode.OR:
            dest = self._op(ops[0])
            src1 = self._op(ops[1])
            src2 = self._op(ops[2])
            if dest == src1:
                return f"or {dest}, {src2}"
            return f"mov eax, {src1}\n    or eax, {src2}\n    mov {dest}, eax"

        elif opcode == IROpcode.XOR:
            dest = self._op(ops[0])
            src1 = self._op(ops[1])
            src2 = self._op(ops[2])
            if dest == src1:
                return f"xor {dest}, {src2}"
            return f"mov eax, {src1}\n    xor eax, {src2}\n    mov {dest}, eax"

        elif opcode == IROpcode.LOAD:
            dest = self._op(ops[0])
            src = self._op(ops[1])
            if not src.startswith('['):
                src = f"[{src}]"
            return f"mov eax, {src}\n    mov {dest}, eax"

        elif opcode == IROpcode.STORE:
            addr = self._op(ops[0])
            src = self._op(ops[1])
            if not addr.startswith('['):
                addr = f"[{addr}]"
            return f"mov eax, {src}\n    mov {addr}, eax"

        return f"; Unknown: {opcode.name}"

    def _op(self, operand):
        if operand.operand_type == IROperandType.TEMPORARY:
            offset = self.current_stack_frame.get_offset(operand.value)
            if offset is not None:
                if self._is_float_type(operand):
                    return f"dword [rbp{offset}]"
                return f"dword [rbp{offset}]"
            return f"dword [rbp-8]"

        elif operand.operand_type == IROperandType.VARIABLE:
            offset = self.current_stack_frame.get_offset(operand.value)
            if offset is not None:
                return f"dword [rbp{offset}]"
            return f"[{operand.value}]"

        elif operand.operand_type == IROperandType.LITERAL:
            val = operand.value
            if isinstance(val, float):
                label = f"LC{len(self.float_literals)}"
                self.float_literals.append((label, val))
                return f"dword [{label}]"
            elif isinstance(val, bool):
                return "1" if val else "0"
            return str(val)

        elif operand.operand_type == IROperandType.GLOBAL:
            return f"[{operand.value}]"

        elif operand.operand_type == IROperandType.LABEL:
            return self._make_label(str(operand.value))

        return str(operand.value)

    def _emit(self, line: str, indent: bool = True):
        if indent:
            self.output.append(f"    {line}")
        else:
            self.output.append(line)